export const ENTITY_TAG_LIST = {
    BAC_RETENTION: "retentionBox",
    BOUCHON_BOUILLEUR: "boilerCap",
    BOUILLEUR: "boiler",    
    V3: "V3",
    V4: "V4",
    V8: "V8",
    V11: "V11",
    V12: "V12",
    V14: "V14",
    V15: "V15",
    V16: "V16",
    BIDON_20_L: "Bidon20L",
    FLEXIBLE_POMPE: "FlexiblePompe",
}